import type { Metadata } from 'next';
// import { Inter } from "next/font/google";
import { Providers } from './providers';
import Navbar from './components/navbar';
import { Box } from '@chakra-ui/react';
import { fonts } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts.roboto.variable}>
      <body>
        <Providers>
          <Box backgroundColor={'dark.100'}>
            <Navbar />
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  );
}
